; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "ClipGPT"
#define MyAppVersion "1.0.1"
#define MyAppPublisher "Colin van Loo"
#define MyAppURL "clipgpt.vanloo.ch"
#define MyAppExeName "ClipGPT.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{8418F7DC-DAB6-46B3-A158-65FB135E19B6}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DisableProgramGroupPage=yes
LicenseFile=C:\Development\clipgpt\LICENSE
InfoAfterFile=C:\Development\clipgpt\README.md
; Remove the following line to run in administrative install mode (install for all users.)
PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
OutputBaseFilename=installer
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Development\clipgpt\bin\Release\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Development\clipgpt\bin\Release\ClipGPT.exe.config"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Development\clipgpt\bin\Release\ClipGPT.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Development\clipgpt\bin\Release\Microsoft.Bcl.AsyncInterfaces.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Development\clipgpt\bin\Release\Microsoft.Bcl.AsyncInterfaces.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Development\clipgpt\bin\Release\Microsoft.Configuration.ConfigurationBuilders.Base.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Development\clipgpt\bin\Release\Microsoft.Configuration.ConfigurationBuilders.Base.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Development\clipgpt\bin\Release\Microsoft.Configuration.ConfigurationBuilders.UserSecrets.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Development\clipgpt\bin\Release\Microsoft.Configuration.ConfigurationBuilders.UserSecrets.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Development\clipgpt\bin\Release\System.Buffers.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Development\clipgpt\bin\Release\System.Buffers.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Development\clipgpt\bin\Release\System.Configuration.ConfigurationManager.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Development\clipgpt\bin\Release\System.Configuration.ConfigurationManager.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Development\clipgpt\bin\Release\System.Memory.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Development\clipgpt\bin\Release\System.Memory.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Development\clipgpt\bin\Release\System.Numerics.Vectors.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Development\clipgpt\bin\Release\System.Numerics.Vectors.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Development\clipgpt\bin\Release\System.Runtime.CompilerServices.Unsafe.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Development\clipgpt\bin\Release\System.Runtime.CompilerServices.Unsafe.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Development\clipgpt\bin\Release\System.Security.AccessControl.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Development\clipgpt\bin\Release\System.Security.AccessControl.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Development\clipgpt\bin\Release\System.Security.Permissions.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Development\clipgpt\bin\Release\System.Security.Permissions.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Development\clipgpt\bin\Release\System.Security.Principal.Windows.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Development\clipgpt\bin\Release\System.Security.Principal.Windows.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Development\clipgpt\bin\Release\System.Text.Encodings.Web.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Development\clipgpt\bin\Release\System.Text.Encodings.Web.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Development\clipgpt\bin\Release\System.Text.Json.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Development\clipgpt\bin\Release\System.Text.Json.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Development\clipgpt\bin\Release\System.Threading.Tasks.Extensions.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Development\clipgpt\bin\Release\System.Threading.Tasks.Extensions.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Development\clipgpt\bin\Release\System.ValueTuple.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Development\clipgpt\bin\Release\System.ValueTuple.xml"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

